DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  ID                INT         NOT NULL AUTO_INCREMENT  PRIMARY KEY,
  USERNAME          VARCHAR     NOT NULL UNIQUE,
  PASSWORD          VARCHAR     NOT NULL
)
